
[materials]
	#Requirement for obtaining Captured Wind. Unit: Block per Tick
	#Range: 0.1 ~ 100.0
	windSpeed = 10.0
	#Requirement for void eye drop
	#Range: 0 ~ 128
	belowVoid = 16
	#Requirement for sun membrane drop
	#Range: 0 ~ 10000
	phantomHeight = 200
	#Requirement for explosion shard drop
	#Range: 1 ~ 10000
	explosionDamage = 80
	#Requirement for space shard drop
	#Range: 1 ~ 1000000
	spaceDamage = 16384

["fire charge"]
	#Soul Fire Charge Duration
	#Range: 1 ~ 10000
	soulFireChargeDuration = 60
	#Black Fire Charge Duration
	#Range: 1 ~ 10000
	blackFireChargeDuration = 100
	#Strong Fire Charge Power
	#Range: 1 ~ 10
	strongFireChargePower = 2

[properties]
	#Totemic Armor healing interval
	#Range: 1 ~ 1000
	totemicHealDuration = 100
	#Totemic Armor healing amount
	#Range: 1 ~ 1000
	totemicHealAmount = 1
	#Wind Sweep enchantment increment to sweep hit box
	#Range: 0.1 ~ 100.0
	windSweepIncrement = 1.0
	#Damage factor of emerald splash
	#Range: 0.001 ~ 1000.0
	emeraldDamageFactor = 0.5
	#Base range for emerald splash
	#Range: 1 ~ 100
	emeraldBaseRange = 10
	#Base duration for iceBlade
	#Range: 1 ~ 10000
	iceEnchantDuration = 100
	#Duration for flameBlade
	#Range: 1 ~ 10000
	flameEnchantDuration = 60
	#Base duration for sharpBlade
	#Range: 1 ~ 10000
	bleedEnchantDuration = 80
	#Base duration for cursedBlade
	#Range: 1 ~ 10000
	curseEnchantDuration = 100
	#Max effect level for sharpBlade
	#Range: 1 ~ 10000
	bleedEnchantMax = 3
	#Void Touch chance for true damage
	#Range: 0.0 ~ 1.0
	voidTouchChance = 0.05
	#Void Touch chance for true damage if bypass armor or magic
	#Range: 0.0 ~ 1.0
	voidTouchChanceBonus = 0.5
	#Bonus damage factor for specific materials against specific mob types
	#Range: 0.0 ~ 1000.0
	mobTypeBonus = 1.0

